services:
  - type: web
    name: online-testing-system
    env: docker
    plan: free
    repo: https://github.com/Mihalkevitc/online_testing_system
    branch: main
    dockerfilePath: ./Dockerfile
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: online-testing-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000

databases:
  - name: online-testing-db
    plan: free
