services:
  - type: web
    name: online-testing-system
    env: docker
    plan: free
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: online-testing-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000

databases:
  - name: online-testing-db
    plan: free
