# Generated by Django 5.2 on 2025-05-01 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы за ответ'),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершено'), ('needs_review', 'Требует проверки'), ('in_progress', 'В процессе')], default='in_progress', max_length=12, verbose_name='Статус'),
        ),
    ]
