# Generated by Django 5.2 on 2025-05-03 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_studentgroup_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
