# Generated by Django 5.2 on 2025-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_teststarttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='Баллы за ответ'),
        ),
    ]
